name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - run: python -m venv venv
    - run: source venv/bin/activate
    - run: pip install -r requirements.txt
    - run: robot .

    - name: deploy to Heroku
      if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
      uses: akhileshns/heroku-deploy@v3.7.8 
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "social-news-site"
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        usedocker: true
        healthcheck: http://social-news-site.herokuapp.com/health
        checkstring: ok
        rollbackonhealthcheckfailed: true

    - uses: actions/checkout@v2
    - name: Bump version and push tag
      if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
      uses: anothrNick/github-tag-action@eca2b69f9e2c24be7decccd0f15fdb1ea5906598
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: patch

    - name: Send a build failure notification to Slack
      uses: 8398a7/action-slack@v3
      if: ${{ failure() }}
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,took
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    
    - name: Send a deployment notification to Slack
      uses: 8398a7/action-slack@v3
      if: ${{ success() && github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
      with:
        status: custom
        fields: commit,author,took
        custom_payload: |
          {
            username: 'github-action',
            icon_emoji: ':100:',
            attachments: [{
              color: 'good',
              text: `a new version deployed to http://social-news-site.herokuapp.com/ (${process.env.AS_COMMIT}) by ${process.env.AS_AUTHOR} succeeded in ${process.env.AS_TOOK}`,
            }]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}